started working on associate-repo feature
MLH-Fellowship/github-discord-bot pull request #33
Opened 2020-11-19 17:21 UTC by diananova

- not finished yet
- working on local JSON file for now

2020-11-20 14:15 UTC, Laurell876 approved these changes
Seems good

2020-11-20 18:46 UTC, gmelodie commented
@diananova quick reminder if your PR is not finished you can make it a Draft PR

2020-11-20 18:55 UTC, gmelodie requested changes
Playing with `async` stuff can get dangerous sometimes :smile:

2020-11-20 18:55 UTC, gmelodie commented on bot.py
> +	reposDict[channel]=repoName
I wonder how dangerous this dict being global is, especially if we're dealing with `async` functions. Perhaps making a function `update_reposDict` that [locks](https://stackoverflow.com/a/25799871/6032037) the variable could be a better way to go

2020-11-20 18:55 UTC, gmelodie commented on bot.py
> +		repo = git.get_repo(repoName)
```suggestion
	if channel not in reposDict:
		repoName = reposDict[channel]
	repo = git.get_repo(repoName)
```

2020-11-21 00:11 UTC, merged

2020-11-21 00:14 UTC, diananova commented
- seems to work in deployed version as well.